# Generated by Django 5.0.6 on 2024-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('babysitting', 'Babysitting'), ('cleaning', 'Cleaning'), ('teaching', 'Teaching'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
