# Generated by Django 5.0.6 on 2024-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='suggested_price',
            field=models.FloatField(default=0.0),
        ),
    ]
